# Generated by Django 6.0.1 on 2026-09-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_voice_character_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='proactive_done',
            field=models.BooleanField(default=False),
        ),
    ]
